"""Add bilingual species name and description columns

Revision ID: 2c414e3f4bfd
Revises: 001
Create Date: 2026-04-12 16:36:03.650326

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c414e3f4bfd'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('species_name_en', sa.String(length=255), server_default='', nullable=False))
    op.add_column('entries', sa.Column('species_name_pt', sa.String(length=255), server_default='', nullable=False))
    op.add_column('entries', sa.Column('description_en', sa.Text(), server_default='', nullable=False))
    op.add_column('entries', sa.Column('description_pt', sa.Text(), server_default='', nullable=False))
    op.execute("UPDATE entries SET species_name_en = species_name, description_en = description")
    op.drop_column('entries', 'description')
    op.drop_column('entries', 'species_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('species_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('entries', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_entries_created_at'), 'entries', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_column('entries', 'description_pt')
    op.drop_column('entries', 'description_en')
    op.drop_column('entries', 'species_name_pt')
    op.drop_column('entries', 'species_name_en')
    # ### end Alembic commands ###
